plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  apollo-utilities@*:
    dependencies:
      graphql: '^15.7.2'
  apollo-codegen-core@*:
    dependencies:
      graphql: '^15.7.2'
  apollo-codegen-swift@*:
    dependencies:
      graphql: '^15.7.2'
  apollo-codegen-flow@*:
    dependencies:
      graphql: '^15.7.2'
  apollo-codegen-typescript@*:
    dependencies:
      graphql: '^15.7.2'
  apollo-codegen-scala@*:
    dependencies:
      graphql: '^15.7.2'
